# Build and push Docker images to Google Container Registry
# Run these steps based off the remote trigger in CloudBuild.
steps:
  # Reservations
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-east4-docker.pkg.dev/rezz-444007/reservations/production', '-f', 'apps/reservations/Dockerfile', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-east4-docker.pkg.dev/rezz-444007/reservations/production']
  # Auth
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-east4-docker.pkg.dev/rezz-444007/auth/production', '-f', 'apps/auth/Dockerfile', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-east4-docker.pkg.dev/rezz-444007/auth/production']
  # Notifications
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-east4-docker.pkg.dev/rezz-444007/notifications/production', '-f', 'apps/notifications/Dockerfile', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-east4-docker.pkg.dev/rezz-444007/notifications/production']
  # Payments
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-east4-docker.pkg.dev/rezz-444007/payments/production', '-f', 'apps/payments/Dockerfile', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-east4-docker.pkg.dev/rezz-444007/payments/production']
options:
  logging: CLOUD_LOGGING_ONLY